; Script generated by Antigravity IDE for Maharashtra Police Legal Intelligence Studio
#define MyAppName "Maharashtra Police - Legal Document Studio"
#define MyAppVersion "4.0.0"
#define MyAppPublisher "Maharashtra Police & Legal Intelligence"
#define MyAppURL "https://github.com/kartikplayzz/Protocol-4"
#define MyAppExeName "Protocol4_Desktop.exe"
#define MySourceDir "E:\Protocol-4\dist\Protocol4_Desktop"
#define MyAssetsDir "E:\Protocol-4\assets"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{B76A93F2-9A4E-4B08-B31F-10257B4D0868}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Output configuration
OutputDir=E:\Protocol-4\installer_output
OutputBaseFilename=Protocol4_Studio_Setup_v4.0.0
SetupIconFile={#MyAssetsDir}\icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Standalone Desktop Bundle Files
Source: "{#MySourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Assets for shortcut and branding
Source: "{#MyAssetsDir}\icon.ico"; DestDir: "{app}\assets"; Flags: ignoreversion
Source: "{#MyAssetsDir}\logo.png"; DestDir: "{app}\assets"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
